### ISSUE TITLE
Get error when running " cargo build --release"

### ISSUE THREAD

**Issue by willow2333** [heathsc/baldur#2]
hi heathsc,
    I get the error as below pic, when I run the command of "cargo build --release". Thank you very much!
![image](https://user-images.githubusercontent.com/47717534/226528207-c780bdc0-b16e-46ab-89e7-2314d30289ba.png)

**Comment by heathsc** [comment]
Your installed version of htslib is too old: hts_flush() was added to htslib in 1.14.  I  am currently using 1.16 and that works fine.

Simon

**Comment by heathsc** [comment]
I have modified the documentation so that the minimum version of htslib is now 1.14.
